test

diff --git a/.github/workflows/test_image.yml b/.github/workflows/test_image.yml
--- a/.github/workflows/test_image.yml
+++ b/.github/workflows/test_image.yml
@@ -31,8 +31,7 @@ jobs:
           status=0
           sleep 10
           while [ $status -ne 200 ]; do
-            curl http://localhost:3000/api/health
-            status=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:3000/api/health)
+            status=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:3000/api/health || echo "curl error")
             if [ $status -eq 200 ]; then
               echo "Service is up with status: $status"
               break
