Test influx config trough gf api

diff --git a/.github/workflows/test_image.yml b/.github/workflows/test_image.yml
--- a/.github/workflows/test_image.yml
+++ b/.github/workflows/test_image.yml
@@ -49,6 +49,22 @@ jobs:
           else
             echo "Files are the same. Continuing."
           fi
+
+      - name: Test in Grafana API if InfluxDB config exists
+        run: |
+          # Fetch the JSON from the Grafana API
+          JSON_FROM_CURL=$(curl -s "http://grafanaadmin:grafanapassword@localhost:3000/api/datasources/1")
+      
+          # Define the expected JSON
+          EXPECTED_JSON='{"id":1,"uid":"P951FEA4DE68E13C5","orgId":1,"name":"InfluxDB","type":"influxdb","typeLogoUrl":"/public/app/plugins/datasource/influxdb/img/influxdb_logo.svg","access":"proxy","url":"http://influxdb:8086","user":"","database":"","basicAuth":false,"basicAuthUser":"","withCredentials":false,"isDefault":true,"jsonData":{"defaultBucket":"testbucket","organization":"testorg","tlsSkipVerify":true,"version":"Flux"},"secureJsonFields":{"token":true},"version":1,"readOnly":true}'
+      
+          # Normalize and compare the JSON
+          if ! diff <(echo $JSON_FROM_CURL | jq --sort-keys .) <(echo $EXPECTED_JSON | jq --sort-keys .) > /dev/null; then
+            echo "JSON structures are different. Failing the step."
+            exit 1
+          else
+            echo "JSON structures are the same. Continuing."
+          fi
       
 
   build_test:
